# backend/agent/state.py

from typing import TypedDict, Annotated
import operator


class AgentState(TypedDict):
    """
    The state that flows through every node in our LangGraph agent.
    Every node reads from and writes to this state.
    """
    # The original user question
    original_question: str

    # Sub-questions generated by the planner
    sub_questions: list[str]

    # Retrieved chunks per sub-question
    # Format: [{"sub_question": str, "chunks": [{"text": str, "metadata": dict}]}]
    retrieved_chunks: list[dict]

    # Reranked and deduplicated final chunks
    final_chunks: list[dict]

    # Whether retrieved context is sufficient to answer
    is_sufficient: bool

    # How many times we've retried retrieval
    retry_count: int

    # The final generated answer
    final_answer: str

    # Sources used in the answer
    sources: list[dict]

    # Error message if something went wrong
    error: str